import 'transaction_status.dart';

enum FinancialEntryType {
  income,
  expense,
  payable,
  receivable,
}

extension FinancialEntryTypeLabel on FinancialEntryType {
  String get label {
    switch (this) {
      case FinancialEntryType.income:
        return 'Pemasukan';
      case FinancialEntryType.expense:
        return 'Pengeluaran';
      case FinancialEntryType.payable:
        return 'Hutang Toko';
      case FinancialEntryType.receivable:
        return 'Piutang Customer';
    }
  }

  String get shortLabel {
    switch (this) {
      case FinancialEntryType.income:
        return 'Masuk';
      case FinancialEntryType.expense:
        return 'Keluar';
      case FinancialEntryType.payable:
        return 'Hutang';
      case FinancialEntryType.receivable:
        return 'Piutang';
    }
  }
}

class FinancialEntry {
  final String id;
  final String title;
  final String description;
  final double amount;
  final DateTime date;
  final FinancialEntryType type;
  final String sourceLabel;
  final String? sourceId;
  final TransactionStatus? status;

  FinancialEntry({
    required this.id,
    required this.title,
    required this.description,
    required this.amount,
    required this.date,
    required this.type,
    this.sourceLabel = 'Manual',
    this.sourceId,
    this.status,
  });

  bool get isAutoGenerated => sourceId != null;

  FinancialEntry copyWith({
    String? id,
    String? title,
    String? description,
    double? amount,
    DateTime? date,
    FinancialEntryType? type,
    String? sourceLabel,
    String? sourceId,
    TransactionStatus? status,
  }) {
    return FinancialEntry(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      amount: amount ?? this.amount,
      date: date ?? this.date,
      type: type ?? this.type,
      sourceLabel: sourceLabel ?? this.sourceLabel,
      sourceId: sourceId ?? this.sourceId,
      status: status ?? this.status,
    );
  }
}

class FinancialSummary {
  final double income;
  final double expense;
  final double payable;
  final double receivable;

  const FinancialSummary({
    required this.income,
    required this.expense,
    required this.payable,
    required this.receivable,
  });

  double get balance => income - expense;
  double get projectedBalance => balance + receivable - payable;
}
