import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../app/routes.dart';
import '../../models/financial_entry.dart';
import '../../providers/app_data_provider.dart';
import '../../utils/constants.dart';
import '../../utils/formatters.dart';
import '../../widgets/empty_state.dart';

class CombinedTransactionListScreen extends StatelessWidget {
  const CombinedTransactionListScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<AppDataProvider>();
    final entries = provider.combinedFinancialEntries;

    if (entries.isEmpty) {
      return const Padding(
        padding: EdgeInsets.all(AppSpacing.screenPadding),
        child: EmptyState(
          icon: Icons.receipt_long_outlined,
          title: 'Belum ada transaksi',
          subtitle: 'Invoice, bon, hutang, dan catatan keuangan manual akan tampil di sini.',
        ),
      );
    }

    return ListView.separated(
      padding: const EdgeInsets.fromLTRB(16, 16, 16, 100),
      itemCount: entries.length,
      separatorBuilder: (_, __) => const SizedBox(height: 12),
      itemBuilder: (context, index) {
        final entry = entries[index];
        final isAutoGenerated = entry.sourceId != null;
        
        final icon = switch (entry.type) {
          FinancialEntryType.income => Icons.south_west_rounded,
          FinancialEntryType.expense => Icons.north_east_rounded,
          FinancialEntryType.payable => Icons.money_off_rounded,
          FinancialEntryType.receivable => Icons.account_balance_wallet_rounded,
        };

        return Card(
          child: ListTile(
            onTap: () {
              if (isAutoGenerated) {
                final route = entry.sourceLabel == 'Hutang Usaha'
                    ? AppRoutes.hutangUsahaDetail
                    : (entry.sourceLabel == 'Hutang'
                        ? AppRoutes.hutangDetail
                        : (entry.sourceLabel == 'Invoice' ? AppRoutes.invoiceDetail : AppRoutes.bonDetail));
                AppRoutes.push(
                  context,
                  route,
                  arguments: entry.sourceId,
                );
              } else {
                AppRoutes.push(context, AppRoutes.financialEntryDetail, arguments: entry.id);
              }
            },
            contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            leading: Container(
              width: 50,
              height: 50,
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primary.withValues(alpha: 0.10),
                borderRadius: BorderRadius.circular(16),
              ),
              child: Icon(
                icon,
                color: Theme.of(context).colorScheme.primary,
              ),
            ),
            title: Text(
              entry.title,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: const TextStyle(fontWeight: FontWeight.w800),
            ),
            subtitle: Padding(
              padding: const EdgeInsets.only(top: 4),
              child: Text(
                '${entry.type.label} • ${entry.sourceLabel} • ${AppFormatters.date(entry.date)}',
              ),
            ),
            trailing: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.end,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  AppFormatters.currency(entry.amount),
                  style: const TextStyle(
                    fontWeight: FontWeight.w900,
                  ),
                ),
                const SizedBox(height: 4),
                if (isAutoGenerated)
                  const Text(
                    'Auto',
                    style: TextStyle(fontSize: 11, fontWeight: FontWeight.w700),
                  )
                else
                  const Text(
                    'Manual',
                    style: TextStyle(fontSize: 11, fontWeight: FontWeight.w700, color: Colors.orange),
                  ),
              ],
            ),
          ),
        );
      },
    );
  }
}
