import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../app/routes.dart';
import '../../models/financial_entry.dart';
import '../../providers/app_data_provider.dart';
import '../../utils/constants.dart';
import '../../utils/formatters.dart';
import '../../widgets/empty_state.dart';
import '../../widgets/search_bar_field.dart';

class CombinedTransactionListScreen extends StatefulWidget {
  const CombinedTransactionListScreen({super.key});

  @override
  State<CombinedTransactionListScreen> createState() => _CombinedTransactionListScreenState();
}

class _CombinedTransactionListScreenState extends State<CombinedTransactionListScreen> {
  String _search = '';

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<AppDataProvider>();
    final entries = provider.combinedFinancialEntries;
    
    final filteredEntries = entries.where((entry) {
      if (_search.isEmpty) return true;
      final q = _search.toLowerCase();
      return entry.title.toLowerCase().contains(q) ||
             entry.description.toLowerCase().contains(q) ||
             entry.sourceLabel.toLowerCase().contains(q);
    }).toList();

    return Padding(
      padding: const EdgeInsets.all(AppSpacing.screenPadding),
      child: Column(
        children: [
          SearchBarField(
            hintText: 'Cari transaksi',
            onChanged: (value) => setState(() => _search = value),
          ),
          const SizedBox(height: 16),
          Expanded(
            child: filteredEntries.isEmpty
                ? const EmptyState(
                    icon: Icons.receipt_long_outlined,
                    title: 'Belum ada transaksi',
                    subtitle: 'Invoice, bon, dan catatan keuangan manual akan tampil di sini.',
                  )
                : ListView.separated(
                    padding: const EdgeInsets.only(bottom: 100),
                    itemCount: filteredEntries.length,
                    separatorBuilder: (_, __) => const SizedBox(height: 12),
                    itemBuilder: (context, index) {
                      final entry = filteredEntries[index];
        final isAutoGenerated = entry.sourceId != null;
        
        final icon = switch (entry.type) {
          FinancialEntryType.income => Icons.south_west_rounded,
          FinancialEntryType.expense => Icons.north_east_rounded,
          FinancialEntryType.payable => Icons.money_off_rounded,
          FinancialEntryType.receivable => Icons.account_balance_wallet_rounded,
        };

        return Card(
          child: ListTile(
            onTap: () {
              if (isAutoGenerated) {
                final route = entry.sourceLabel == 'Hutang Usaha'
                    ? AppRoutes.hutangUsahaDetail
                    : (entry.sourceLabel == 'Invoice' ? AppRoutes.invoiceDetail : AppRoutes.bonDetail);
                AppRoutes.push(
                  context,
                  route,
                  arguments: entry.sourceId,
                );
              } else {
                AppRoutes.push(context, AppRoutes.financialEntryDetail, arguments: entry.id);
              }
            },
            contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            leading: Container(
              width: 50,
              height: 50,
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primary.withValues(alpha: 0.10),
                borderRadius: BorderRadius.circular(16),
              ),
              child: Icon(
                icon,
                color: Theme.of(context).colorScheme.primary,
              ),
            ),
            title: Text(
              entry.title,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: const TextStyle(fontWeight: FontWeight.w800),
            ),
            subtitle: Padding(
              padding: const EdgeInsets.only(top: 4),
              child: Text(
                '${entry.type.label} • ${entry.sourceLabel} • ${AppFormatters.date(entry.date)}',
              ),
            ),
            trailing: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.end,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  AppFormatters.currency(entry.amount),
                  style: const TextStyle(
                    fontWeight: FontWeight.w900,
                  ),
                ),
                const SizedBox(height: 4),
                if (isAutoGenerated)
                  const Text(
                    'Auto',
                    style: TextStyle(fontSize: 11, fontWeight: FontWeight.w700),
                  )
                else
                  const Text(
                    'Manual',
                    style: TextStyle(fontSize: 11, fontWeight: FontWeight.w700, color: Colors.orange),
                  ),
              ],
            ),
          ),
        );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
